apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fetchr.fullname" . }}
  labels:
    {{- include "fetchr.labels" . | nindent 4 }}
data:
  FETCHR_LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  FETCHR_SKIP_LOGIN: {{ .Values.app.skipLogin | quote }}
  FETCHR_SESSION_TTL: {{ .Values.app.sessionTtl | quote }}
  FETCHR_COOKIE_SECURE: {{ .Values.app.cookieSecure | quote }}
  FETCHR_MAX_UPLOAD_SIZE: {{ .Values.app.maxUploadSize | quote }}
  FETCHR_MAX_CONNECTIONS: {{ .Values.app.maxConnections | quote }}
  FETCHR_DIAL_TIMEOUT: {{ .Values.app.dialTimeout | quote }}
  FETCHR_INSECURE_HOST_KEY: {{ .Values.app.insecureHostKey | quote }}
  FETCHR_ALLOWED_HOSTS: {{ join "," .Values.app.allowedHosts | quote }}
  {{- if not .Values.app.skipLogin }}
  FETCHR_OIDC_ISSUER: {{ .Values.oidc.issuer | quote }}
  FETCHR_OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  FETCHR_OIDC_REDIRECT_URL: {{ .Values.oidc.redirectUrl | quote }}
  FETCHR_OIDC_SCOPES: {{ .Values.oidc.scopes | quote }}
  {{- end }}
