apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftpweb.fullname" . }}
  labels:
    {{- include "sftpweb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if eq .Values.service.sessionAffinity "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeoutSeconds }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "sftpweb.selectorLabels" . | nindent 4 }}
